# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDDingDingClock' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDDingDingClock
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'Alamofire-SwiftyJSON'
  pod 'RongCloudIM/IMLib'
  pod 'NVActivityIndicatorView'
  pod 'SVProgressHUD'

  target 'DDDingDingClockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDDingDingClockUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
